# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designShip2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 576)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Matura MT Script Capitals"))
        font.setPointSize(20)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout.addWidget(self.label_32)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        # setting margins around window and around content
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setContentsMargins(20, 10, 10, 10)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 8, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 9, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 10, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 11, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 12, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 13, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 14, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 15, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 6, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 7, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 8, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 9, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 10, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 11, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 12, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 13, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 14, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 15, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        # setting margins around window and around content
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setContentsMargins(10, 10, 20, 10)
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 0, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 0, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 0, 4, 1, 1)
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 0, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 0, 6, 1, 1)
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 0, 7, 1, 1)
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 0, 8, 1, 1)
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 0, 9, 1, 1)
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 0, 10, 1, 1)
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_2.addWidget(self.label_43, 0, 11, 1, 1)
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_2.addWidget(self.label_44, 0, 12, 1, 1)
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_2.addWidget(self.label_45, 0, 13, 1, 1)
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_2.addWidget(self.label_46, 0, 14, 1, 1)
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_2.addWidget(self.label_47, 0, 15, 1, 1)
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_2.addWidget(self.label_48, 1, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.centralwidget)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_2.addWidget(self.label_49, 2, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_2.addWidget(self.label_50, 3, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.centralwidget)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_2.addWidget(self.label_51, 4, 0, 1, 1)
        self.label_52 = QtGui.QLabel(self.centralwidget)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_2.addWidget(self.label_52, 5, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.centralwidget)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_2.addWidget(self.label_53, 6, 0, 1, 1)
        self.label_54 = QtGui.QLabel(self.centralwidget)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_2.addWidget(self.label_54, 7, 0, 1, 1)
        self.label_55 = QtGui.QLabel(self.centralwidget)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_2.addWidget(self.label_55, 8, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.centralwidget)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_2.addWidget(self.label_56, 9, 0, 1, 1)
        self.label_57 = QtGui.QLabel(self.centralwidget)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_2.addWidget(self.label_57, 10, 0, 1, 1)
        self.label_58 = QtGui.QLabel(self.centralwidget)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_2.addWidget(self.label_58, 11, 0, 1, 1)
        self.label_59 = QtGui.QLabel(self.centralwidget)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_2.addWidget(self.label_59, 12, 0, 1, 1)
        self.label_60 = QtGui.QLabel(self.centralwidget)
        self.label_60.setFont(font)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_2.addWidget(self.label_60, 13, 0, 1, 1)
        self.label_61 = QtGui.QLabel(self.centralwidget)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_2.addWidget(self.label_61, 14, 0, 1, 1)
        self.label_62 = QtGui.QLabel(self.centralwidget)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_2.addWidget(self.label_62, 15, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_2.setContentsMargins(0, 10, 20, 10)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout.addWidget(self.radioButton_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton.setStyleSheet(_fromUtf8("QPushButton {\nbackground-color: #4682B4;\nborder-style: outset;\nborder-width: 2px;\nborder-radius: 10px;\nborder-color: beige;\nfont: bold 10px;\ncolor: beige;\nwidth: 100px;\nheight: 30px;\n}"))
        self.pushButton.setEnabled(False)
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        # list of all buttons for computer
        self.buttonGroup = QtGui.QButtonGroup(self)
        for i in range(225):
            button = QtGui.QToolButton(self.centralwidget)
            sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(button.sizePolicy().hasHeightForWidth())
            button.setSizePolicy(sizePolicy)
            button.setText(_fromUtf8(""))
            button.setObjectName(_fromUtf8("toolButton_" + str(i)))
            button.setEnabled(False)
            self.gridLayout.addWidget(button, i / 15 + 1, i % 15 + 1, 1, 1)
            self.buttonGroup.addButton(button)

        # list of all buttons for player
        self.buttonGroupPlayer = QtGui.QButtonGroup(self)
        for i in range(225):
            button = QtGui.QToolButton(self.centralwidget)
            sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(button.sizePolicy().hasHeightForWidth())
            button.setSizePolicy(sizePolicy)
            button.setText(_fromUtf8(""))
            button.setObjectName(_fromUtf8("toolButton_" + str(i + 225)))
            button.setEnabled(False)
            self.gridLayout_2.addWidget(button, i / 15 + 1, i % 15 + 1, 1, 1)
            self.buttonGroupPlayer.addButton(button)

        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.actionNew_Game = QtGui.QAction(MainWindow)
        self.actionNew_Game.setObjectName(_fromUtf8("actionNew_Game"))
        self.actionNew_Game.setShortcut("Ctrl+N")
        self.actionSave_Game = QtGui.QAction(MainWindow)
        self.actionSave_Game.setObjectName(_fromUtf8("actionSave_Game"))
        self.actionSave_Game.setShortcut("Ctrl+S")
        self.actionSave_Game.setEnabled(False)
        self.actionLoad_Game = QtGui.QAction(MainWindow)
        self.actionLoad_Game.setObjectName(_fromUtf8("actionLoad_Game"))
        self.actionLoad_Game.setShortcut("Ctrl+L")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionQuit.setShortcut("Ctrl+Q")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addAction(self.actionSave_Game)
        self.menuFile.addAction(self.actionLoad_Game)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Battleship", None))
        self.label_31.setText(_translate("MainWindow", "Computer", None))
        self.label_32.setText(_translate("MainWindow", "Player", None))
        self.label.setText(_translate("MainWindow", "A", None))
        self.label_2.setText(_translate("MainWindow", "B", None))
        self.label_3.setText(_translate("MainWindow", "C", None))
        self.label_4.setText(_translate("MainWindow", "D", None))
        self.label_5.setText(_translate("MainWindow", "E", None))
        self.label_6.setText(_translate("MainWindow", "F", None))
        self.label_7.setText(_translate("MainWindow", "G", None))
        self.label_8.setText(_translate("MainWindow", "H", None))
        self.label_9.setText(_translate("MainWindow", "I", None))
        self.label_10.setText(_translate("MainWindow", "J", None))
        self.label_11.setText(_translate("MainWindow", "K", None))
        self.label_12.setText(_translate("MainWindow", "L", None))
        self.label_13.setText(_translate("MainWindow", "M", None))
        self.label_14.setText(_translate("MainWindow", "N", None))
        self.label_15.setText(_translate("MainWindow", "O", None))
        self.label_16.setText(_translate("MainWindow", "1", None))
        self.label_17.setText(_translate("MainWindow", "2", None))
        self.label_18.setText(_translate("MainWindow", "3", None))
        self.label_19.setText(_translate("MainWindow", "4", None))
        self.label_20.setText(_translate("MainWindow", "5", None))
        self.label_21.setText(_translate("MainWindow", "6", None))
        self.label_22.setText(_translate("MainWindow", "7", None))
        self.label_23.setText(_translate("MainWindow", "8", None))
        self.label_24.setText(_translate("MainWindow", "9", None))
        self.label_25.setText(_translate("MainWindow", "10", None))
        self.label_26.setText(_translate("MainWindow", "11", None))
        self.label_27.setText(_translate("MainWindow", "12", None))
        self.label_28.setText(_translate("MainWindow", "13", None))
        self.label_29.setText(_translate("MainWindow", "14", None))
        self.label_30.setText(_translate("MainWindow", "15", None))
        self.label_33.setText(_translate("MainWindow", "A", None))
        self.label_34.setText(_translate("MainWindow", "B", None))
        self.label_35.setText(_translate("MainWindow", "C", None))
        self.label_36.setText(_translate("MainWindow", "D", None))
        self.label_37.setText(_translate("MainWindow", "E", None))
        self.label_38.setText(_translate("MainWindow", "F", None))
        self.label_39.setText(_translate("MainWindow", "G", None))
        self.label_40.setText(_translate("MainWindow", "H", None))
        self.label_41.setText(_translate("MainWindow", "I", None))
        self.label_42.setText(_translate("MainWindow", "J", None))
        self.label_43.setText(_translate("MainWindow", "K", None))
        self.label_44.setText(_translate("MainWindow", "L", None))
        self.label_45.setText(_translate("MainWindow", "M", None))
        self.label_46.setText(_translate("MainWindow", "N", None))
        self.label_47.setText(_translate("MainWindow", "O", None))
        self.label_48.setText(_translate("MainWindow", "1", None))
        self.label_49.setText(_translate("MainWindow", "2", None))
        self.label_50.setText(_translate("MainWindow", "3", None))
        self.label_51.setText(_translate("MainWindow", "4", None))
        self.label_52.setText(_translate("MainWindow", "5", None))
        self.label_53.setText(_translate("MainWindow", "6", None))
        self.label_54.setText(_translate("MainWindow", "7", None))
        self.label_55.setText(_translate("MainWindow", "8", None))
        self.label_56.setText(_translate("MainWindow", "9", None))
        self.label_57.setText(_translate("MainWindow", "10", None))
        self.label_58.setText(_translate("MainWindow", "11", None))
        self.label_59.setText(_translate("MainWindow", "12", None))
        self.label_60.setText(_translate("MainWindow", "13", None))
        self.label_61.setText(_translate("MainWindow", "14", None))
        self.label_62.setText(_translate("MainWindow", "15", None))
        self.radioButton.setText(_translate("MainWindow", "Ship of length 5", None))
        self.radioButton_2.setText(_translate("MainWindow", "Ship of length 4", None))
        self.radioButton_3.setText(_translate("MainWindow", "Ship of length 3", None))
        self.radioButton_4.setText(_translate("MainWindow", "Ship of length 3", None))
        self.radioButton_5.setText(_translate("MainWindow", "Ship of length 2", None))
        self.pushButton.setText(_translate("MainWindow", "Start Game", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game", None))
        self.actionSave_Game.setText(_translate("MainWindow", "Save Game", None))
        self.actionLoad_Game.setText(_translate("MainWindow", "Load Game", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))